# Database Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_catalogue
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

# Actuator Config
management:
  endpoints:
    web:
      exposure:
        include: "*"